// [WARNING] This file is generated by running `$ qore codegen` on your root project, please do not edit

/// <reference types="@feedloop/qore-client" />
import { QoreSchema } from "@feedloop/qore-client";

declare module "@feedloop/qore-client" {
  type KategoriTableRow = {
    id: string;
    nama: string;
    banner: { nodes: BannerTableRow[] };
  };

  type BannerTableRow = {
    id: string;
    namaBanner: string;
    imageBanner: string;
    kategoriProduk: { nodes: KategoriProdukTableRow[] };
    namaMitra: NamaMitraTableRow;
    namaKategori: string;
    mitra: string;
  };

  type TraceAbilityTableRow = {
    id: string;
    lokasi: string;
    nama: string;
    cara: string;
    tanggal: Date;
    namaMitra: NamaMitraTableRow;
    mitra: string;
  };

  type KabupatenTableRow = {
    id: string;
    kabupaten: string;
    kecamatan: { nodes: KecamatanTableRow[] };
  };

  type ProdukTableRow = {
    id: string;
    namaBarang: string;
    gambarBarang: string;
    usiaBarang: number;
    deskripsiBarang: string;
    hargaBarang: number;
    stokBarang: number;
    beratBarang: number;
    namaMitra: NamaMitraTableRow;
    keranjang: { nodes: KeranjangTableRow[] };
    mitra: string;
  };

  type MemberTableRow = {
    id: string;
    email: string;
    role: { id: string; displayField: string };
    password: string;
    nama: string;
    alamat: string;
    noHp: number;
    keranjang1: { nodes: Keranjang1TableRow[] };
  };

  type KelurahanTableRow = {
    id: string;
    kelurahan: string;
    kecamatanId: KecamatanIdTableRow;
    ongkosKirim: number;
  };

  type KeranjangTableRow = {
    id: string;
    produkId: ProdukIdTableRow;
    userId: UserIdTableRow;
    kuantiti: number;
    gambarBarang: string;
    hargaBarang: number;
    namaBarang: string;
    statusTransaksi: string;
    namaProduk: string;
    orderId: number;
  };

  type MitraTableRow = {
    id: string;
    namaLengkap: string;
    alamat: string;
    noHp: number;
    noTelp: number;
    email: string;
    nilaiBagiHasil: number;
    traceAbility: { nodes: TraceAbilityTableRow[] };
    produk: { nodes: ProdukTableRow[] };
    banner1: { nodes: Banner1TableRow[] };
  };

  type KecamatanTableRow = {
    id: string;
    kecamatan: string;
    kabupatenId: KabupatenIdTableRow;
    kelurahan: { nodes: KelurahanTableRow[] };
  };

  type BuktiBayarTableRow = {
    id: string;
    fileBukti: string;
    nama: string;
    orderId: number;
    email: string;
  };

  type AllMemberViewRow = {
    read: {
      id: string;
      email: string;
      role: { id: string; displayField: string };
      password: string;
      nama: string;
      alamat: string;
      noHp: number;
    };
    write: {
      email: string;
      password: string;
      nama: string;
      alamat: string;
      noHp: number;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllMitraViewRow = {
    read: {
      id: string;
      namaLengkap: string;
      alamat: string;
      noHp: number;
      noTelp: number;
      email: string;
      nilaiBagiHasil: number;
    };
    write: {
      namaLengkap: string;
      alamat: string;
      noHp: number;
      noTelp: number;
      email: string;
      nilaiBagiHasil: number;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type KeranjangViewRow = {
    read: {
      id: string;
      produkId: ProdukIdTableRow;
      userId: UserIdTableRow;
      kuantiti: number;
    };
    write: {
      produkId: string[];
      userId: string[];
      kuantiti: number;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllBannerViewRow = {
    read: {
      id: string;
      namaBanner: string;
      imageBanner: string;
      kategoriProduk: { nodes: KategoriProdukTableRow[] };
      namaMitra: NamaMitraTableRow;
      namaKategori: string;
      mitra: string;
    };
    write: {
      namaBanner: string;
      imageBanner: string;
      kategoriProduk: string[];
      namaMitra: string[];
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllTraceAbilityViewRow = {
    read: {
      id: string;
      lokasi: string;
      nama: string;
      cara: string;
      tanggal: Date;
      namaMitra: NamaMitraTableRow;
      mitra: string;
    };
    write: {
      lokasi: string;
      nama: string;
      cara: string;
      tanggal: Date;
      namaMitra: string[];
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllProdukViewRow = {
    read: {
      id: string;
      namaBarang: string;
      gambarBarang: string;
      usiaBarang: number;
      deskripsiBarang: string;
      hargaBarang: number;
      stokBarang: number;
      beratBarang: number;
      namaMitra: NamaMitraTableRow;
      mitra: string;
    };
    write: {
      namaBarang: string;
      gambarBarang: string;
      usiaBarang: number;
      deskripsiBarang: string;
      hargaBarang: number;
      stokBarang: number;
      beratBarang: number;
      namaMitra: string[];
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllKategoriViewRow = {
    read: {
      id: string;
      nama: string;
    };
    write: {
      nama: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllKabupatenViewRow = {
    read: {
      id: string;
      kabupaten: string;
    };
    write: {
      kabupaten: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllKecamatanViewRow = {
    read: {
      id: string;
      kecamatan: string;
      kabupatenId: KabupatenIdTableRow;
    };
    write: {
      kecamatan: string;
      kabupatenId: string[];
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllKelurahanViewRow = {
    read: {
      id: string;
      kelurahan: string;
      kecamatanId: KecamatanIdTableRow;
      ongkosKirim: number;
    };
    write: {
      kelurahan: string;
      kecamatanId: string[];
      ongkosKirim: number;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type AllKeranjangViewRow = {
    read: {
      id: string;
      produkId: ProdukIdTableRow;
      userId: UserIdTableRow;
      kuantiti: number;
      gambarBarang: string;
      hargaBarang: number;
      statusTransaksi: string;
      namaProduk: string;
      orderId: number;
    };
    write: {
      produkId: string[];
      userId: string[];
      kuantiti: number;
      statusTransaksi: string;
      orderId: number;
    };
    params: {
      userId?: string;
    };
    actions: {};
    forms: {};
  };

  type AllPembayaranViewRow = {
    read: {
      id: string;
      fileBukti: string;
      nama: string;
      orderId: number;
      email: string;
    };
    write: {
      fileBukti: string;
      nama: string;
      orderId: number;
      email: string;
    };
    params: {};
    actions: {};
    forms: {};
  };

  type MyKeranjangViewRow = {
    read: {
      id: string;
      produkId: ProdukIdTableRow;
      userId: UserIdTableRow;
      kuantiti: number;
      gambarBarang: string;
      hargaBarang: number;
      namaBarang: string;
    };
    write: {
      produkId: string[];
      userId: string[];
      kuantiti: number;
    };
    params: {
      userId?: string;
    };
    actions: {};
    forms: {};
  };

  type ProjectSchema = {
    allMember: AllMemberViewRow;
    allMitra: AllMitraViewRow;
    keranjang: KeranjangViewRow;
    allBanner: AllBannerViewRow;
    allTraceAbility: AllTraceAbilityViewRow;
    allProduk: AllProdukViewRow;
    allKategori: AllKategoriViewRow;
    allKabupaten: AllKabupatenViewRow;
    allKecamatan: AllKecamatanViewRow;
    allKelurahan: AllKelurahanViewRow;
    allKeranjang: AllKeranjangViewRow;
    allPembayaran: AllPembayaranViewRow;
    myKeranjang: MyKeranjangViewRow;
  };
}
